/* Sample character data — a small roster covering different classes */

const CHARACTERS = [
  {
    id: "thurin",
    name: "Thurin Ferroscudo",
    race: "Nano",
    klass: "Guerriero",
    level: 1,
    alignment: "CE",
    hp: { current: 12, max: 12 },
    xp: { current: 0, max: 1000 },
    ca: 12,
    bab: 1,
    init: 2,
    stats: { FOR: 15, DES: 14, COS: 15, INT: 12, SAG: 12, CAR: 6 },
    statBreakdown: {
      FOR: { base: 15, race: 0, total: 15, label: "Forza" },
      DES: { base: 14, race: 0, total: 14, label: "Destrezza" },
      COS: { base: 13, race: 2, total: 15, label: "Costituzione", note: "+2 razziale" },
      INT: { base: 12, race: 0, total: 12, label: "Intelligenza" },
      SAG: { base: 10, race: 2, total: 12, label: "Saggezza", note: "+2 razziale" },
      CAR: { base: 8, race: -2, total: 6, label: "Carisma", note: "-2 razziale" },
    },
    saves: {
      tempra: { base: 2, ability: 2, magic: 0, total: 4 },
      riflessi: { base: 0, ability: 2, magic: 0, total: 2 },
      volonta: { base: 0, ability: 1, magic: 0, total: 1 },
    },
    weapons: [
      { name: "Ascia da battaglia", type: "Marziale a una mano", attack: "+4", damage: "1d8+2", critical: "x3" },
      { name: "Pugnale", type: "Semplice da lancio", attack: "+3", damage: "1d4+2", critical: "19-20/x2" },
      { name: "Balestra leggera", type: "Marziale a distanza", attack: "+3", damage: "1d8", critical: "19-20/x2" },
    ],
    abilities: [
      { name: "Intimidire", base: "CAR", trained: true, ranks: 1, mod: -2, total: 2 },
      { name: "Percezione", base: "SAG", trained: false, ranks: 0, mod: 1, total: 1 },
      { name: "Scalare", base: "FOR", trained: true, ranks: 1, mod: 2, total: 6 },
      { name: "Sopravvivenza", base: "SAG", trained: true, ranks: 1, mod: 1, total: 5 },
      { name: "Conoscenze (geografia)", base: "INT", trained: true, ranks: 1, mod: 1, total: 5 },
      { name: "Cavalcare", base: "DES", trained: false, ranks: 0, mod: 2, total: 2 },
      { name: "Artigianato (armi)", base: "INT", trained: true, ranks: 1, mod: 1, total: 5 },
      { name: "Furtività", base: "DES", trained: false, ranks: 0, mod: 2, total: 2 },
    ],
    capacities: [
      { name: "Talento bonus da guerriero", type: "Capacità di classe", uses: null, desc: "Al 1° livello, un guerriero ottiene un talento bonus oltre a quelli concessi dalla normale progressione e dal talento di razza." },
      { name: "Resistenza dei Nani", type: "Tratto razziale", uses: null, desc: "+2 ai tiri salvezza contro veleni, incantesimi e capacità magiche." },
      { name: "Odio Atavico", type: "Tratto razziale", uses: null, desc: "+1 ai tiri per colpire contro creature umanoidi del sottotipo orco o goblinoide." },
      { name: "Visione nel Buio", type: "Tratto razziale", uses: null, desc: "I nani vedono perfettamente in assenza totale di luce fino a 18 metri." },
      { name: "Stabilità", type: "Tratto razziale", uses: null, desc: "+4 alla CMD contro tentativi di travolgere o sbilanciare quando il nano è a terra." },
    ],
    spells: [],
    notes: "Thurin viene dalle montagne del nord, esiliato dal suo clan dopo essersi rifiutato di lasciar morire un compagno orco ferito. Ora vaga in cerca di un nuovo scopo, portando con sé l'ascia di suo padre e un cuore più caldo di quanto vorrebbe ammettere.",
  },
  {
    id: "lyra",
    name: "Lyra Voltastella",
    race: "Mezzelfo",
    klass: "Mago",
    level: 3,
    alignment: "NB",
    hp: { current: 14, max: 18 },
    xp: { current: 2700, max: 3300 },
    ca: 13,
    bab: 1,
    init: 3,
    stats: { FOR: 8, DES: 14, COS: 12, INT: 17, SAG: 13, CAR: 12 },
    statBreakdown: {
      FOR: { base: 8, race: 0, total: 8, label: "Forza" },
      DES: { base: 14, race: 0, total: 14, label: "Destrezza" },
      COS: { base: 12, race: 0, total: 12, label: "Costituzione" },
      INT: { base: 15, race: 2, total: 17, label: "Intelligenza", note: "+2 razziale" },
      SAG: { base: 13, race: 0, total: 13, label: "Saggezza" },
      CAR: { base: 12, race: 0, total: 12, label: "Carisma" },
    },
    saves: {
      tempra: { base: 1, ability: 1, magic: 0, total: 2 },
      riflessi: { base: 1, ability: 2, magic: 0, total: 3 },
      volonta: { base: 3, ability: 1, magic: 0, total: 4 },
    },
    weapons: [
      { name: "Bastone arcano", type: "Semplice a una mano", attack: "+0", damage: "1d6-1", critical: "x2" },
      { name: "Dardo", type: "Semplice da lancio", attack: "+3", damage: "1d4-1", critical: "x2" },
    ],
    abilities: [
      { name: "Conoscenze (arcane)", base: "INT", trained: true, ranks: 3, mod: 3, total: 9 },
      { name: "Conoscenze (storia)", base: "INT", trained: true, ranks: 3, mod: 3, total: 9 },
      { name: "Percezione", base: "SAG", trained: false, ranks: 0, mod: 1, total: 3 },
      { name: "Scrivere magia", base: "INT", trained: true, ranks: 3, mod: 3, total: 9 },
      { name: "Diplomazia", base: "CAR", trained: true, ranks: 2, mod: 1, total: 5 },
    ],
    capacities: [
      { name: "Famiglio Arcano", type: "Capacità di classe", uses: null, desc: "Lyra ha legato a sé un piccolo gufo, Tessitore, che fornisce +3 ai tiri di Percezione." },
      { name: "Specializzazione: Evocazione", type: "Scuola arcana", uses: null, desc: "Specializzata nell'evocare creature dai piani esterni. +1 incantesimo al giorno per livello di evocazione." },
      { name: "Sangue Élfico", type: "Tratto razziale", uses: null, desc: "Conta come elfo per qualsiasi effetto correlato alla razza." },
      { name: "Convocazione Estatica", type: "Capacità di scuola", uses: 7, used: 2, desc: "Azione standard: aggiunge +1/2 livello al danno di una creatura evocata per 1 round." },
    ],
    spells: [
      { level: 0, slots: 4, prepared: [
        { name: "Luce", school: "Evocazione", desc: "Crea una luce mistica della stessa intensità di una torcia." },
        { name: "Mano Magica", school: "Trasmutazione", desc: "Solleva e muove un oggetto fino a 2,5 kg a distanza." },
        { name: "Folata di Vento", school: "Evocazione", desc: "Una raffica di aria spinge le creature leggere indietro." },
        { name: "Lettura del Magico", school: "Divinazione", desc: "Permette di leggere rune e iscrizioni arcane." },
      ]},
      { level: 1, slots: 3, used: 1, prepared: [
        { name: "Dardo Incantato", school: "Evocazione", desc: "1d4+1 danni a un bersaglio scelto. Non manca mai." },
        { name: "Scudo Arcano", school: "Astrazione", desc: "+4 CA per 1 minuto, blocca i dardi incantati." },
        { name: "Sonno", school: "Ammaliamento", desc: "Mette a dormire 4 DV di creature umanoidi." },
      ]},
      { level: 2, slots: 2, used: 0, prepared: [
        { name: "Immagine Speculare", school: "Illusione", desc: "Crea 1d4+1 immagini duplicate di Lyra." },
        { name: "Invisibilità", school: "Illusione", desc: "Il bersaglio diventa invisibile per 3 minuti." },
      ]},
    ],
    notes: "Studiosa nata in una biblioteca di Absalom, Lyra cerca un grimorio perduto che potrebbe svelare l'origine del suo dono per l'evocazione. Tessitore, il gufo, la segue ovunque.",
  },
  {
    id: "kael",
    name: "Kael Ombrasvelta",
    race: "Halfling",
    klass: "Ladro",
    level: 2,
    alignment: "CN",
    hp: { current: 11, max: 14 },
    xp: { current: 1500, max: 2000 },
    ca: 16,
    bab: 1,
    init: 5,
    stats: { FOR: 10, DES: 17, COS: 12, INT: 13, SAG: 12, CAR: 14 },
    statBreakdown: {
      FOR: { base: 12, race: -2, total: 10, label: "Forza", note: "-2 razziale" },
      DES: { base: 15, race: 2, total: 17, label: "Destrezza", note: "+2 razziale" },
      COS: { base: 12, race: 0, total: 12, label: "Costituzione" },
      INT: { base: 13, race: 0, total: 13, label: "Intelligenza" },
      SAG: { base: 12, race: 0, total: 12, label: "Saggezza" },
      CAR: { base: 12, race: 2, total: 14, label: "Carisma", note: "+2 razziale" },
    },
    saves: {
      tempra: { base: 0, ability: 1, magic: 0, total: 1 },
      riflessi: { base: 3, ability: 3, magic: 1, total: 7, note: "+1 razziale" },
      volonta: { base: 0, ability: 1, magic: 1, total: 2, note: "+1 razziale" },
    },
    weapons: [
      { name: "Spada corta", type: "Marziale leggera", attack: "+4", damage: "1d6", critical: "19-20/x2" },
      { name: "Arco corto", type: "Marziale a distanza", attack: "+4", damage: "1d6", critical: "x3" },
      { name: "Pugnale da lancio", type: "Semplice", attack: "+4", damage: "1d4", critical: "19-20/x2" },
    ],
    abilities: [
      { name: "Furtività", base: "DES", trained: true, ranks: 2, mod: 3, total: 13, note: "+4 size" },
      { name: "Acrobazia", base: "DES", trained: true, ranks: 2, mod: 3, total: 9 },
      { name: "Disattivare Congegni", base: "DES", trained: true, ranks: 2, mod: 3, total: 8 },
      { name: "Scassinare Serrature", base: "DES", trained: true, ranks: 2, mod: 3, total: 8 },
      { name: "Percezione", base: "SAG", trained: true, ranks: 2, mod: 1, total: 8 },
      { name: "Raggirare", base: "CAR", trained: true, ranks: 2, mod: 2, total: 8 },
    ],
    capacities: [
      { name: "Attacco Furtivo +1d6", type: "Capacità di classe", uses: null, desc: "+1d6 danni quando l'avversario è colto alla sprovvista o privo di Destrezza in CA." },
      { name: "Talento Ladresco", type: "Capacità di classe", uses: null, desc: "Al 2° livello scegli un talento speciale: Kael ha preso 'Mossa Furtiva'." },
      { name: "Bersaglio Difficile", type: "Tratto razziale", uses: null, desc: "+1 CA contro le creature di taglia Media o superiore." },
      { name: "Coraggio degli Halfling", type: "Tratto razziale", uses: null, desc: "+1 ai tiri salvezza contro paura." },
    ],
    spells: [],
    notes: "Cresciuto nei vicoli di Westcrown, Kael ha imparato presto che l'unico modo di restare libero era essere invisibile. Cerca ora vendetta contro la casata che ha ucciso suo padre — un debito da saldare al chiaro di luna.",
  },
];

Object.assign(window, { CHARACTERS });
